AC_CONFIG_FILES([
	src/modules/database/hash/Makefile
	src/modules/protocol/sip/Makefile
	src/modules/protocol/sip/captureplan/Makefile
	src/modules/protocol/rtcp/Makefile
	src/modules/protocol/rtcp/captureplan/Makefile
	src/modules/socket/pcap/Makefile
	src/modules/socket/raw/Makefile
	src/modules/socket/rtcpxr/Makefile
	src/modules/socket/rtcpxr/captureplan/Makefile
	src/modules/transport/hep/Makefile
	src/modules/transport/json/Makefile
])
